"""initial_schema_with_composite_indexes

Revision ID: 17d06ec9074d
Revises: 
Create Date: 2026-09-26 22:24:12.574590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d06ec9074d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_bid_timestamp', ['bid_id', 'timestamp'], unique=False)

    with op.batch_alter_table('bid_documents', schema=None) as batch_op:
        batch_op.create_index('ix_bid_documents_assigned_status', ['assigned_reviewer_id', 'review_status'], unique=False)
        batch_op.create_index('ix_bid_documents_bid_req', ['bid_id', 'requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bid_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_foreign_key('fk_bid_documents_reviewed_by', 'users', ['reviewed_by'], ['id'])
        batch_op.create_foreign_key('fk_bid_documents_assigned_reviewer_id', 'users', ['assigned_reviewer_id'], ['id'])

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index('ix_bids_tender_status', ['tender_id', 'submission_status'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_department'), ['department'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_department'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index('ix_bids_tender_status')

    with op.batch_alter_table('bid_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bid_documents_assigned_reviewer_id', type_='foreignkey')
        batch_op.drop_constraint('fk_bid_documents_reviewed_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bid_documents_content_hash'))
        batch_op.drop_index('ix_bid_documents_bid_req')
        batch_op.drop_index('ix_bid_documents_assigned_status')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_bid_timestamp')

    # ### end Alembic commands ###

