"""initial_schema_with_composite_indexes

Revision ID: 17d06ec9074d
Revises: 
Create Date: 2026-09-26 22:24:12.574590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d06ec9074d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema idempotently."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    def has_index(table_name, index_name):
        if table_name not in tables:
            return False
        return any(idx.get('name') == index_name for idx in inspector.get_indexes(table_name))

    def has_fk(table_name, fk_name):
        if table_name not in tables:
            return False
        return any(fk.get('name') == fk_name for fk in inspector.get_foreign_keys(table_name))

    if 'audit_logs' in tables:
        with op.batch_alter_table('audit_logs', schema=None) as batch_op:
            if not has_index('audit_logs', 'ix_audit_logs_bid_timestamp'):
                batch_op.create_index('ix_audit_logs_bid_timestamp', ['bid_id', 'timestamp'], unique=False)

    if 'bid_documents' in tables:
        with op.batch_alter_table('bid_documents', schema=None) as batch_op:
            if not has_index('bid_documents', 'ix_bid_documents_assigned_status'):
                batch_op.create_index('ix_bid_documents_assigned_status', ['assigned_reviewer_id', 'review_status'], unique=False)
            if not has_index('bid_documents', 'ix_bid_documents_bid_req'):
                batch_op.create_index('ix_bid_documents_bid_req', ['bid_id', 'requirement_id'], unique=False)
            if not has_index('bid_documents', 'ix_bid_documents_content_hash'):
                batch_op.create_index(batch_op.f('ix_bid_documents_content_hash'), ['content_hash'], unique=False)
            if not has_fk('bid_documents', 'fk_bid_documents_reviewed_by'):
                batch_op.create_foreign_key('fk_bid_documents_reviewed_by', 'users', ['reviewed_by'], ['id'])
            if not has_fk('bid_documents', 'fk_bid_documents_assigned_reviewer_id'):
                batch_op.create_foreign_key('fk_bid_documents_assigned_reviewer_id', 'users', ['assigned_reviewer_id'], ['id'])

    if 'bids' in tables:
        with op.batch_alter_table('bids', schema=None) as batch_op:
            if not has_index('bids', 'ix_bids_tender_status'):
                batch_op.create_index('ix_bids_tender_status', ['tender_id', 'submission_status'], unique=False)

    if 'notifications' in tables:
        with op.batch_alter_table('notifications', schema=None) as batch_op:
            if not has_index('notifications', 'ix_notifications_user_read'):
                batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    if 'users' in tables:
        with op.batch_alter_table('users', schema=None) as batch_op:
            if not has_index('users', 'ix_users_department'):
                batch_op.create_index(batch_op.f('ix_users_department'), ['department'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_department'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index('ix_bids_tender_status')

    with op.batch_alter_table('bid_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bid_documents_assigned_reviewer_id', type_='foreignkey')
        batch_op.drop_constraint('fk_bid_documents_reviewed_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bid_documents_content_hash'))
        batch_op.drop_index('ix_bid_documents_bid_req')
        batch_op.drop_index('ix_bid_documents_assigned_status')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_bid_timestamp')

    # ### end Alembic commands ###

